all:maze.o findcheese_iter.o createMaze.o
	gcc -o ex maze.o findcheese_iter.o createMaze.o 	

maze.o:maze.c
	gcc -c maze.c

findcheese_iter.o:findcheese_iter.c
	gcc -c findcheese_iter.c

createMaze.o:createMaze.c
	gcc -c createMaze.c	
